version: "3"
services:
  nomo-poject:
    image: webwil/nomo-poject
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: webwil/mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
